### ISSUE TITLE
How is CRC16 implemented?

### ISSUE THREAD

**Issue by SebastianStehle** [snksoft/crc#4]
Hi,

we use your package in a server and do not understand why it actually works.

We have the following code to calculate the CRC:

```
package main

import "fmt"

import "github.com/snksoft/crc"

func main() {
	replyWindow := "\"ACK\"0033L0#00201398[]"

	crc2 := crc.CalculateCRC(crc.CRC16, []byte(replyWindow))
	crcHex := fmt.Sprintf("%x", crc2)

	fmt.Println(crcHex)
}
```

Output: `CA56`

But I cannot reproduce it with other implementations, e.g. https://crccalc.com/

**Comment by snksoft** [comment]
It's called CRC-16/ARC on crccalc.com and I see the result matching. Though I suspect you have already figured that out.

**Comment by SebastianStehle** [comment]
Yes, exactly ;)
