### ISSUE TITLE
How to install v1.1

### ISSUE THREAD

**Issue by zeasly** [snksoft/crc#7]
thanks for help
go get https://github.com/snksoft/crc default install v1.0.1
how to install v1.1.

**Comment by snksoft** [comment]
That's a bit weird - `go get github.com/snksoft/crc` should install the latest version and that is 1.1.

What I suspect to be an issue is that if you already have an older version then go get won't update it. You need to specify -u flag like this: `go get -u github.com/snksoft/crc`

Note that it may still fail to update to the latest version if you have made some local modifications to the code or replaced some files. If that's the case, then find and delete snksoft/crc folder and then `go get github.com/snksoft/crc` again. It will fetch the latest version. But make sure you make a copy of your changes (if any) before deleting the files.

I have just re-tested all 3 scenarios above on my machine and they all worked as expected.

Let me know if it helped.

**Comment by zeasly** [comment]
It's not work. Maybe because I used go mod?
[https://youtu.be/q8a9Lj2H7Z8](https://youtu.be/q8a9Lj2H7Z8)

**Comment by snksoft** [comment]
Looks like the issue is that go mod requires version tag to have exactly 3 numbers. I have created a new tag for that and it seems both new and old ways are working correctly now. But you will need to update your go.mod file for any existing project to point to the new version.

**Comment by zeasly** [comment]
it's work.  thanks
